In [542]:
inp_a = 0#0,6,9
inp_b = 10#5,8,10
dimn = inp_b-inp_a+1

# Data Preprocessing Tools

## Importing the Libraries

In [543]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

## Importing the Dataset

In [544]:
np.random.seed(seed=7)
# hp = pd.read_csv('hp_all_time_domain_s4_std.csv',header = None)
# f1 = pd.read_csv('f1_all_time_domain_s4_std.csv',header = None)
# ip = pd.read_csv('if_all_time_domain_s4_std.csv',header = None)
# out = pd.read_csv("output_features_speed_wise.csv",header=None)

hp_e = pd.read_csv('hp_all_time_domain_s7_entropy.csv',header = None)
f1_e = pd.read_csv('f1_all_time_domain_s7_entropy.csv',header = None)
ip_e = pd.read_csv('if_all_time_domain_s7_entropy.csv',header = None)
out_e = pd.read_csv("output_features_speed_wise.csv",header=None)

hp = pd.read_csv('hp_all_time_domain_s7_mean.csv',header = None)
f1 = pd.read_csv('f1_all_time_domain_s7_mean.csv',header = None)
ip = pd.read_csv('if_all_time_domain_s7_mean.csv',header = None)
out = pd.read_csv("output_features_speed_wise.csv",header=None)

hp=hp.append(f1,ignore_index=True)
hp=hp.append(ip,ignore_index=True)
hp=hp.append(hp_e,ignore_index=True)
hp=hp.append(f1_e,ignore_index=True)
hp=hp.append(ip_e,ignore_index=True)

out=out.append(out_e,ignore_index=True)

C:\Users\HP\AppData\Local\Temp\ipykernel_24948\2897327085.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  hp=hp.append(f1,ignore_index=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_24948\2897327085.py:18: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  hp=hp.append(ip,ignore_index=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_24948\2897327085.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  hp=hp.append(hp_e,ignore_index=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_24948\2897327085.py:20: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  hp=hp.append(f1_e,ignore_index=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_24948\289732708

In [545]:
out.shape

(5400, 1)

In [546]:
hp.shape      #append all the fault files as ecah has 6300 rows with 11 columns  [6300*3=18900]

(5400, 11)

In [547]:
hp.head()

0         1         2         3         4         5         6   \
0  0.000232 -0.000199  0.000414  0.000195 -0.000140 -0.000279 -0.000072   
1  0.000209 -0.000217  0.000359  0.000156 -0.000136 -0.000250 -0.000060   
2  0.000195 -0.000213  0.000402  0.000136 -0.000118 -0.000235 -0.000043   
3  0.000229 -0.000179  0.000387  0.000185 -0.000105 -0.000236 -0.000081   
4  0.000213 -0.000219  0.000429  0.000202 -0.000104 -0.000238 -0.000075   

         7         8         9         10  
0  0.000564 -0.000611  0.404311  0.382805  
1  0.000604 -0.000607  0.404246  0.382222  
2  0.000629 -0.000601  0.404396  0.382268  
3  0.000610 -0.000574  0.403966  0.382132  
4  0.000593 -0.000550  0.404186  0.382542

### Adding output columns 

In [548]:
df = pd.concat([hp,out],axis = 1, ignore_index=True)
df.head()

0         1         2         3         4         5         6   \
0  0.000232 -0.000199  0.000414  0.000195 -0.000140 -0.000279 -0.000072   
1  0.000209 -0.000217  0.000359  0.000156 -0.000136 -0.000250 -0.000060   
2  0.000195 -0.000213  0.000402  0.000136 -0.000118 -0.000235 -0.000043   
3  0.000229 -0.000179  0.000387  0.000185 -0.000105 -0.000236 -0.000081   
4  0.000213 -0.000219  0.000429  0.000202 -0.000104 -0.000238 -0.000075   

         7         8         9         10  11  
0  0.000564 -0.000611  0.404311  0.382805   1  
1  0.000604 -0.000607  0.404246  0.382222   1  
2  0.000629 -0.000601  0.404396  0.382268   1  
3  0.000610 -0.000574  0.403966  0.382132   1  
4  0.000593 -0.000550  0.404186  0.382542   1

In [549]:
df.shape        #earlier the column were 11, now it becomes 12

(5400, 12)

### Defining x,y

In [550]:
X = df.iloc[:, :-1].values  
y = df.iloc[:, -1].values

In [551]:
print(X)

[[ 2.32459487e-04 -1.99011200e-04  4.13745537e-04 ... -6.10602130e-04
   4.04310685e-01  3.82804505e-01]
 [ 2.09424116e-04 -2.17139195e-04  3.59221168e-04 ... -6.07068087e-04
   4.04246431e-01  3.82222004e-01]
 [ 1.95489364e-04 -2.12744530e-04  4.01989807e-04 ... -6.01446577e-04
   4.04395703e-01  3.82267580e-01]
 ...
 [ 1.89533691e+00  1.86756194e+00  1.34356398e+00 ...  2.28166961e+00
   2.16990287e+00  3.09931568e+00]
 [ 1.83882482e+00  1.81149400e+00  1.37567381e+00 ...  2.27944806e+00
   2.07493368e+00  2.88567187e+00]
 [ 1.86485419e+00  1.84595315e+00  1.36417266e+00 ...  2.28485691e+00
   2.28250806e+00  3.17096880e+00]]


In [552]:
print(y)

[ 1  1  1 ... 18 18 18]


## Splitting the dataset into the Training set and Test set

In [553]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [554]:
print(X_train)

[[ 1.80929224e+00  1.68200799e+00  1.64114657e+00 ...  2.56471114e+00
   3.02309976e+00  3.28407919e+00]
 [ 1.88134295e+00  1.73916842e+00  1.34372892e+00 ...  2.49680712e+00
   2.93586177e+00  3.63132926e+00]
 [ 1.95629749e-04 -2.13354900e-04  4.07025361e-04 ... -5.51853999e-04
   4.03857894e-01  3.82622095e-01]
 ...
 [ 1.77907528e+00  1.71846136e+00  1.66116430e+00 ...  2.56675652e+00
   2.99408660e+00  3.35881657e+00]
 [ 2.01422163e-04 -1.97387616e-04  3.05020295e-04 ... -3.65123447e-04
   3.99697879e-01  3.78446693e-01]
 [ 1.89820504e+00  1.96061525e+00  1.42427445e+00 ...  2.32838404e+00
   2.98492548e+00  3.49192603e+00]]


In [555]:
print(y_train)

[ 9 15  1 ...  9  2 17]


In [556]:
print(X_test)

[[ 1.83581448e+00  1.78733872e+00  1.74379620e+00 ...  2.57091183e+00
   3.22403958e+00  3.40891203e+00]
 [ 2.20935698e-04 -1.72795801e-04  3.94457839e-04 ... -7.44651631e-04
   3.89627351e-01  3.80297891e-01]
 [ 1.89937171e+00  1.90855992e+00  1.38514767e+00 ...  2.51599269e+00
   3.41030283e+00  4.04914032e+00]
 ...
 [ 2.18396558e-04 -1.29129917e-04  3.40629292e-04 ... -4.03375347e-04
   2.26153661e-01  2.28468972e-01]
 [ 2.12524796e-04 -2.02746666e-04  3.75933103e-04 ... -5.92681661e-04
   4.04456142e-01  3.82255702e-01]
 [ 1.75080182e+00  1.69900062e+00  1.60262263e+00 ...  2.30654502e+00
   2.70770291e+00  2.80463995e+00]]


In [557]:
print(y_test)

[ 8  7 16 ...  6  1 12]


## Feature Scaling

In [558]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [559]:
print(X_train)

[[ 1.09460648  1.04673418  1.1747213  ...  1.0745015   0.98128639
   0.87851976]
 [ 1.17745175  1.1156814   0.78208033 ...  1.0196211   0.91778139
   1.09684605]
 [-0.98552694 -0.98237044 -0.99132892 ... -0.9987582  -0.92539388
  -0.94571131]
 ...
 [ 1.05986245  1.09070443  1.20114806 ...  1.07615459  0.96016623
   0.92550934]
 [-0.98552028 -0.98235118 -0.99146358 ... -0.99860729 -0.92842216
  -0.94833651]
 [ 1.1968401   1.38279177  0.88841389 ...  0.88350064  0.95349738
   1.00919916]]


In [560]:
print(X_test)

[[ 1.12510226  1.17378467  1.31023596 ...  1.07951293  1.12756077
   0.95700582]
 [-0.98549784 -0.98232152 -0.99134551 ... -0.99891402 -0.93575302
  -0.9471726 ]
 [ 1.19818156  1.32000235  0.83676    ...  1.03512698  1.26315133
   1.3595361 ]
 ...
 [-0.98550076 -0.98226885 -0.99141657 ... -0.9986382  -1.05475389
  -1.04263189]
 [-0.98550752 -0.98235765 -0.99136996 ... -0.9987912  -0.92495838
  -0.94594167]
 [ 1.02735309  1.06723078  1.12386327 ...  0.86585022  0.75169287
   0.57708227]]


## Training the Random Forest Classification model on the Training set

In [561]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

In [562]:
y_pred = classifier.predict(X_test)

In [563]:
 from sklearn.metrics import accuracy_score
(accuracy_score (y_test,y_pred))*100


99.72222222222223